In [2]:
"""

merge student.csv and scores.csv 
average score per subject with groupby
average score per city(needs the merge first)
which students score >= 90 in any subject


"""

'\n\nmerge student.csv and scores.csv \naverage score per subject with groupby\naverage score per city(needs the merge first)\nwhich students score >= 90 in any subject\n\n\n'

In [3]:
import numpy as np
import pandas as pd

In [4]:
students = pd.read_csv(r"D:\Ai engineering course\Notebooks\students.csv")

In [5]:
students

   id      name       city
0   1      Yash    pokhara
1   2  Priyanka   lalitpur
2   3     Samip  bharatpur
3   4     Akash    pokhara
4   5     Varun   lalitpur
5   6     Samir  bharatpur
6   7    Aayush   lalitpur
7   8     Suman    hetauda
8   9       Ram  bharatpur
9  10      Sita  dhangadhi

In [6]:
scores = pd.read_csv(r"D:\Ai engineering course\Notebooks\scores.csv")

In [7]:
scores

   id    subject  score
0   1       Math     95
1   2    Science     88
2   3    English     76
3   4   Computer     99
4   5    Physics     84
5   6    Physics     91
6   7   Computer     73
7   8  Economics     80
8   9       Math     69
9  10    English     87

In [8]:
ggg = pd.merge(students, scores, on = "id")

In [9]:
ggg

   id      name       city    subject  score
0   1      Yash    pokhara       Math     95
1   2  Priyanka   lalitpur    Science     88
2   3     Samip  bharatpur    English     76
3   4     Akash    pokhara   Computer     99
4   5     Varun   lalitpur    Physics     84
5   6     Samir  bharatpur    Physics     91
6   7    Aayush   lalitpur   Computer     73
7   8     Suman    hetauda  Economics     80
8   9       Ram  bharatpur       Math     69
9  10      Sita  dhangadhi    English     87

In [10]:
ggg.groupby("subject")["score"].mean()

subject
Computer     86.0
Economics    80.0
English      81.5
Math         82.0
Physics      87.5
Science      88.0
Name: score, dtype: float64

In [11]:
ggg.groupby("city")["score"].mean()

city
bharatpur    78.666667
dhangadhi    87.000000
hetauda      80.000000
lalitpur     81.666667
pokhara      97.000000
Name: score, dtype: float64

In [12]:
high_scores = ggg[ggg['score'] >= 90]

In [13]:
high_scores

   id   name       city   subject  score
0   1   Yash    pokhara      Math     95
3   4  Akash    pokhara  Computer     99
5   6  Samir  bharatpur   Physics     91

In [32]:
ggg.groupby('city').agg({'score': 'mean', 'name': 'count'})

               score  name
city
bharatpur  78.666667     3
dhangadhi  87.000000     1
hetauda    80.000000     1
lalitpur   81.666667     3
pokhara    97.000000     2

In [48]:
ggg.sort_values( by = 'score', ascending = False)

   id      name       city    subject  score
3   4     Akash    pokhara   Computer     99
0   1      Yash    pokhara       Math     95
5   6     Samir  bharatpur    Physics     91
1   2  Priyanka   lalitpur    Science     88
9  10      Sita  dhangadhi    English     87
4   5     Varun   lalitpur    Physics     84
7   8     Suman    hetauda  Economics     80
2   3     Samip  bharatpur    English     76
6   7    Aayush   lalitpur   Computer     73
8   9       Ram  bharatpur       Math     69

In [49]:
ggg.to_csv("city.csv" , index = False)