In [7]:
import numpy as np
import pandas as pd

In [37]:
students = pd.DataFrame({
    "id":[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "name" :["Yash","Priyanka","Samip","Akash","Varun","Samir","Aayush","Suman","Ram","Sita"],
    "city":["pokhara", "lalitpur", "bharatpur", "pokhara", "lalitpur", "bharatpur", "lalitpur", "hetauda", "bharatpur", "dhangadhi"]
})

In [38]:
students

   id      name       city
0   1      Yash    pokhara
1   2  Priyanka   lalitpur
2   3     Samip  bharatpur
3   4     Akash    pokhara
4   5     Varun   lalitpur
5   6     Samir  bharatpur
6   7    Aayush   lalitpur
7   8     Suman    hetauda
8   9       Ram  bharatpur
9  10      Sita  dhangadhi

In [39]:
scores = pd.DataFrame({
    "id": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "subject": [
        "Math",
        "Science",
        "English",
        "Computer",
        "Physics",
        "Physics",
        "Computer",
        "Economics",
        "Math",
        "English"
    ],
    "score": [95, 88, 76, 99, 84, 91, 73, 80, 69, 87]
})

In [40]:
scores

   id    subject  score
0   1       Math     95
1   2    Science     88
2   3    English     76
3   4   Computer     99
4   5    Physics     84
5   6    Physics     91
6   7   Computer     73
7   8  Economics     80
8   9       Math     69
9  10    English     87

In [41]:
new_merged = pd.merge(
    students, scores,
    on = "id")

In [42]:
new_merged

   id      name       city    subject  score
0   1      Yash    pokhara       Math     95
1   2  Priyanka   lalitpur    Science     88
2   3     Samip  bharatpur    English     76
3   4     Akash    pokhara   Computer     99
4   5     Varun   lalitpur    Physics     84
5   6     Samir  bharatpur    Physics     91
6   7    Aayush   lalitpur   Computer     73
7   8     Suman    hetauda  Economics     80
8   9       Ram  bharatpur       Math     69
9  10      Sita  dhangadhi    English     87

In [44]:
students.to_csv("students.csv", index = False)

In [45]:
scores.to_csv("scores.csv" , index = False)