In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("/Users/kbshal/Downloads/machine-readable-business-employment-data-mar-2026-quarter.csv")

In [4]:
df

,Series_reference,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,BDCQ.SEA1AA,2011.06,80078.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
1,BDCQ.SEA1AA,2011.09,78324.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
2,BDCQ.SEA1AA,2011.12,85850.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
3,BDCQ.SEA1AA,2012.03,90743.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
4,BDCQ.SEA1AA,2012.06,81780.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26054,BDCQ.SEE3999A,2017.06,NaN,Y,F,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,Filled jobs (workplace location based),Area Outside Territorial Authority,Actual,NaN,NaN
26055,BDCQ.SEE3999A,2017.09,NaN,Y,F,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,Filled jobs (workplace location based),Area Outside Territorial Authority,Actual,NaN,NaN
26056,BDCQ.SEE3999A,2017.12,NaN,Y,F,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,Filled jobs (workplace location based),Area Outside Territorial Authority,Actual,NaN,NaN
26057,BDCQ.SEE3999A,2018.03,NaN,Y,F,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,Filled jobs (workplace location based),Area Outside Territorial Authority,Actual,NaN,NaN
26058,BDCQ.SEE3999A,2018.06,NaN,Y,F,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,Filled jobs (workplace location based),Area Outside Territorial Authority,Actual,NaN,NaN

In [6]:
df.head()

,Series_reference,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,BDCQ.SEA1AA,2011.06,80078.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
1,BDCQ.SEA1AA,2011.09,78324.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
2,BDCQ.SEA1AA,2011.12,85850.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
3,BDCQ.SEA1AA,2012.03,90743.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
4,BDCQ.SEA1AA,2012.06,81780.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN

In [5]:
df.describe()

,Period,Data_value,Magnitude,Series_title_4,Series_title_5
count,26059.000000,2.322000e+04,26059.000000,0.0,0.0
mean,2018.036443,7.401802e+04,2.249280,NaN,NaN
std,4.280631,2.142554e+05,2.904607,NaN,NaN
min,2011.060000,1.171797e+00,0.000000,NaN,NaN
25%,2014.120000,1.980660e+03,0.000000,NaN,NaN
50%,2018.060000,1.426550e+04,0.000000,NaN,NaN
75%,2022.030000,6.141550e+04,6.000000,NaN,NaN
max,2026.030000,2.321295e+06,6.000000,NaN,NaN

In [14]:
df.head()

,Series_reference,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,BDCQ.SEA1AA,2011.06,80078.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
1,BDCQ.SEA1AA,2011.09,78324.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
2,BDCQ.SEA1AA,2011.12,85850.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
3,BDCQ.SEA1AA,2012.03,90743.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
4,BDCQ.SEA1AA,2012.06,81780.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN

In [15]:
df

,Series_reference,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,BDCQ.SEA1AA,2011.06,80078.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
1,BDCQ.SEA1AA,2011.09,78324.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
2,BDCQ.SEA1AA,2011.12,85850.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
3,BDCQ.SEA1AA,2012.03,90743.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
4,BDCQ.SEA1AA,2012.06,81780.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26054,BDCQ.SEE3999A,2017.06,NaN,Y,F,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,Filled jobs (workplace location based),Area Outside Territorial Authority,Actual,NaN,NaN
26055,BDCQ.SEE3999A,2017.09,NaN,Y,F,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,Filled jobs (workplace location based),Area Outside Territorial Authority,Actual,NaN,NaN
26056,BDCQ.SEE3999A,2017.12,NaN,Y,F,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,Filled jobs (workplace location based),Area Outside Territorial Authority,Actual,NaN,NaN
26057,BDCQ.SEE3999A,2018.03,NaN,Y,F,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,Filled jobs (workplace location based),Area Outside Territorial Authority,Actual,NaN,NaN
26058,BDCQ.SEE3999A,2018.06,NaN,Y,F,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,Filled jobs (workplace location based),Area Outside Territorial Authority,Actual,NaN,NaN

In [21]:
my_separate_df = df.groupby("Series_reference").get_group("BDCQ.SEA1AA")

In [23]:
my_separate_df['Data_value'].mean()

np.float64(93150.21666666666)

In [46]:


students = pd.DataFrame({
    "id":[0,1,2,3,4,5,6],
    "name": ["Bishal", "Sita", "Shyam", "Harry", "Gita", "Joe", "Laviz"],
    "city": ["Kathmandu", "Pokhara", "Chitwan", "Mahendranagar", "Nuwakot", "Biratnagar", "Butwal"]
})


scores = pd.DataFrame({
    "id":[0,1,2,3,4,5,6],
    "name": ["Maths", "Science", "Nepali", "Grammar", "Moral", "English", "Social"],
    "score": [1, 2, 3, 4, 5, 6, 7]
})

In [47]:
students

   id    name           city
0   0  Bishal      Kathmandu
1   1    Sita        Pokhara
2   2   Shyam        Chitwan
3   3   Harry  Mahendranagar
4   4    Gita        Nuwakot
5   5     Joe     Biratnagar
6   6   Laviz         Butwal

In [48]:
scores

   id     name  score
0   0    Maths      1
1   1  Science      2
2   2   Nepali      3
3   3  Grammar      4
4   4    Moral      5
5   5  English      6
6   6   Social      7

In [51]:
new_merged = pd.merge(
    students, scores,
    on="id"
   )

In [52]:
new_merged

   id  name_x           city   name_y  score
0   0  Bishal      Kathmandu    Maths      1
1   1    Sita        Pokhara  Science      2
2   2   Shyam        Chitwan   Nepali      3
3   3   Harry  Mahendranagar  Grammar      4
4   4    Gita        Nuwakot    Moral      5
5   5     Joe     Biratnagar  English      6
6   6   Laviz         Butwal   Social      7

In [55]:
df.isna().sum()

Series_reference        0
Period                  0
Data_value           2839
Suppressed          23220
STATUS                  0
UNITS                   0
Magnitude               0
Subject                 0
Group                   0
Series_title_1          0
Series_title_2          0
Series_title_3          0
Series_title_4      26059
Series_title_5      26059
dtype: int64

In [58]:
df.dropna()

Empty DataFrame
Columns: [Series_reference, Period, Data_value, Suppressed, STATUS, UNITS, Magnitude, Subject, Group, Series_title_1, Series_title_2, Series_title_3, Series_title_4, Series_title_5]
Index: []

In [66]:
df['Series_title_4']=df['Series_title_4'].fillna(0)

In [70]:
df['Series_title_5']=df['Series_title_5'].fillna(df['Data_value'].mean())

In [71]:
df

,Series_reference,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,BDCQ.SEA1AA,2011.06,80078.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,0.0,74018.024483
1,BDCQ.SEA1AA,2011.09,78324.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,0.0,74018.024483
2,BDCQ.SEA1AA,2011.12,85850.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,0.0,74018.024483
3,BDCQ.SEA1AA,2012.03,90743.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,0.0,74018.024483
4,BDCQ.SEA1AA,2012.06,81780.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,0.0,74018.024483
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26054,BDCQ.SEE3999A,2017.06,NaN,Y,F,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,Filled jobs (workplace location based),Area Outside Territorial Authority,Actual,0.0,74018.024483
26055,BDCQ.SEE3999A,2017.09,NaN,Y,F,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,Filled jobs (workplace location based),Area Outside Territorial Authority,Actual,0.0,74018.024483
26056,BDCQ.SEE3999A,2017.12,NaN,Y,F,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,Filled jobs (workplace location based),Area Outside Territorial Authority,Actual,0.0,74018.024483
26057,BDCQ.SEE3999A,2018.03,NaN,Y,F,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,Filled jobs (workplace location based),Area Outside Territorial Authority,Actual,0.0,74018.024483
26058,BDCQ.SEE3999A,2018.06,NaN,Y,F,Number,0,Business Data Collection - BDC,Territorial authority by employment variable,Filled jobs (workplace location based),Area Outside Territorial Authority,Actual,0.0,74018.024483

In [29]:
(df.groupby("Data_value").get_group(abs(df['Data_value'][0])))

,Series_reference,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,BDCQ.SEA1AA,2011.06,80078.0,NaN,F,Number,0,Business Data Collection - BDC,Industry by employment variable,Filled jobs,"Agriculture, Forestry and Fishing",Actual,NaN,NaN